### ISSUE TITLE
[Profiles] Make profile public/private

### ISSUE THREAD

**Issue by afogel** [agency-of-learning/PairApp#182]
Blocked until #179 , #180, and #181 are finished.
Adds ability to make accessing the custom profile public or private.

- [ ] When Private, user without permission should get redirected
- [ ] When Private, users with permission should be shown profile
- [ ] When Private, profile owner (and only profile owner) should be shown a button to toggle profile from private to public
- [ ] When Public, all users should be shown
- [ ] When Public, profile owner (and only profile owner) should be shown a button to toggle profile from public to private

**Comment by toyhammered** [comment]
> Blocked until #179 , #180, and #181 are finished. Adds ability to make accessing the custom profile public or private.
> 
> * [ ]  When Private, users with permission should be shown profile

I'd like to keep this even simpler. When private, only owner and admin can see. No need for any permissions or anything initially.
